# SPDX-License-Identifier: GPL-3.0-or-later
from __future__ import annotations

import os
from pathlib import Path

APP_NAME = "StormFuse"

# src/stormfuse/_version.py is generated by scripts/write_version.py at
# build/install time and is gitignored.
try:
    from stormfuse._version import __version__ as _GENERATED_VERSION
except ImportError:
    _GENERATED_VERSION = "0.0.0+dev"

APP_VERSION = _GENERATED_VERSION
ORG_NAME = "Winds of Storm"
LOG_UPLOAD_ENDPOINT = "https://stormfuse.jasmer.tools"
LOG_UPLOAD_ENABLED = True
AUTO_CHECK_UPDATES = True
ALLOW_PRERELEASE_UPDATES = False
DEBUG_FFMPEG_LOGGING = False


def _log_root() -> Path:
    local_app_data = os.environ.get("LOCALAPPDATA", "")
    if local_app_data:
        return Path(local_app_data) / APP_NAME / "logs"
    xdg_data_home = os.environ.get("XDG_DATA_HOME", "")
    if xdg_data_home:
        return Path(xdg_data_home) / APP_NAME / "logs"
    return Path.home() / ".local" / "share" / APP_NAME / "logs"


LOG_DIR: Path = _log_root()
MAX_LOG_FILES: int = 20


def ffmpeg_report_path(tool_name: str, job_id: str) -> Path:
    """Return the per-job FFREPORT path for *tool_name*."""
    return LOG_DIR / f"{tool_name}-{job_id}.log"
