#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Write src/stormfuse/_version.py from a release tag or git describe.

The runtime version of StormFuse is no longer stored in source. This script is
the only thing that writes `_version.py`, which is gitignored. The CI release
pipeline invokes it with --tag vX.Y.Z; the Makefile invokes it with no args for
local development builds so the editable install resolves a sensible version.

Resolution order:
  1. --tag vX.Y.Z is provided    -> use X.Y.Z exactly
  2. `git describe` succeeds     -> derive "<base>+dev.g<sha>[.dirty]"
  3. No git, no tags             -> "0.0.0+dev"
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

DEFAULT_DEV_VERSION = "0.0.0+dev"
TAG_RE = re.compile(r"^v(\d+\.\d+\.\d+)$")


def parse_tag(tag: str) -> str:
    match = TAG_RE.match(tag)
    if not match:
        raise SystemExit(f"--tag must be vX.Y.Z, got {tag!r}")
    return match.group(1)


def _git(args: list[str], cwd: Path) -> str | None:
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=cwd,
            check=True,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return None
    return result.stdout.strip() or None


def derive_dev_version(repo_root: Path) -> str:
    if not (repo_root / ".git").exists():
        return DEFAULT_DEV_VERSION

    describe = _git(
        ["describe", "--tags", "--match=v[0-9]*.[0-9]*.[0-9]*", "--dirty=.dirty", "--always"],
        repo_root,
    )
    if not describe:
        return DEFAULT_DEV_VERSION

    # On an exact tag: "v1.2.3" or "v1.2.3.dirty"
    exact = re.match(r"^v(\d+\.\d+\.\d+)(\.dirty)?$", describe)
    if exact:
        version = exact.group(1)
        return f"{version}+dev.dirty" if exact.group(2) else version

    # Between tags: "v1.2.3-4-gabcdef1[.dirty]"
    between = re.match(r"^v(\d+\.\d+\.\d+)-(\d+)-g([0-9a-f]+)(\.dirty)?$", describe)
    if between:
        base, count, sha = between.group(1), between.group(2), between.group(3)
        dirty = ".dirty" if between.group(4) else ""
        return f"{base}+dev.{count}.g{sha}{dirty}"

    # No tags reachable: "abcdef1[.dirty]"
    bare = re.match(r"^([0-9a-f]+)(\.dirty)?$", describe)
    if bare:
        sha = bare.group(1)
        dirty = ".dirty" if bare.group(2) else ""
        return f"0.0.0+dev.g{sha}{dirty}"

    return DEFAULT_DEV_VERSION


def write_version_file(version: str, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        "# SPDX-License-Identifier: GPL-3.0-or-later\n"
        "# Generated by scripts/write_version.py. Do not edit. Do not commit.\n"
        f'__version__ = "{version}"\n',
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tag", help="Release tag (vX.Y.Z) to write verbatim")
    parser.add_argument("--root", default=".", help="Repository root (default: cwd)")
    args = parser.parse_args()

    repo_root = Path(args.root).resolve()
    if args.tag:
        version = parse_tag(args.tag)
    else:
        version = derive_dev_version(repo_root)

    target = repo_root / "src" / "stormfuse" / "_version.py"
    write_version_file(version, target)
    print(version)
    return 0


if __name__ == "__main__":
    sys.exit(main())
