# SPDX-License-Identifier: GPL-3.0-or-later
"""Tests for installer compliance assets (§2.3, §12.2, §14)."""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]


def test_required_license_files_exist_with_full_text() -> None:
    license_root = REPO_ROOT / "resources" / "licenses"

    gpl3_text = (license_root / "GPL-3.0.txt").read_text(encoding="utf-8")
    gpl2_text = (license_root / "GPL-2.0.txt").read_text(encoding="utf-8")

    assert "GNU GENERAL PUBLIC LICENSE" in gpl3_text
    assert "Version 3, 29 June 2007" in gpl3_text
    assert "GNU GENERAL PUBLIC LICENSE" in gpl2_text
    assert "Version 2, June 1991" in gpl2_text
    assert "omitted for brevity" not in gpl2_text


def test_installer_notice_files_and_icon_exist() -> None:
    third_party = REPO_ROOT / "resources" / "licenses" / "THIRD-PARTY.md"
    icon_path = REPO_ROOT / "resources" / "icons" / "stormfuse.ico"
    root_license = REPO_ROOT / "LICENSE"

    third_party_text = third_party.read_text(encoding="utf-8")

    assert root_license.exists()
    assert "Generated by `build/generate_third_party.py`" in third_party_text
    assert "FFmpeg (gyan.dev essentials build)" in third_party_text
    assert icon_path.read_bytes()[:4] == b"\x00\x00\x01\x00"


def test_nsis_script_offers_optional_desktop_shortcut() -> None:
    script_path = REPO_ROOT / "build" / "installer" / "stormfuse.nsi"
    script = script_path.read_text(encoding="utf-8")

    assert "!insertmacro MUI_PAGE_COMPONENTS" in script
    assert 'Section /o "Desktop shortcut" SEC02' in script
    assert 'CreateShortcut "$DESKTOP\\${APP_NAME}.lnk" "$INSTDIR\\StormFuse.exe"' in script


def test_nsis_finish_page_can_launch_stormfuse() -> None:
    script_path = REPO_ROOT / "build" / "installer" / "stormfuse.nsi"
    script = script_path.read_text(encoding="utf-8")

    assert '!define MUI_FINISHPAGE_RUN "$WINDIR\\explorer.exe"' in script
    assert '!define MUI_FINISHPAGE_RUN_PARAMETERS "$INSTDIR\\StormFuse.exe"' in script
    assert '!define MUI_FINISHPAGE_RUN_TEXT "Launch ${APP_NAME} v${APP_VERSION}"' in script
    assert "!insertmacro MUI_PAGE_FINISH" in script


def test_nsis_uninstaller_can_optionally_remove_app_data() -> None:
    script_path = REPO_ROOT / "build" / "installer" / "stormfuse.nsi"
    script = script_path.read_text(encoding="utf-8")

    assert "UninstPage custom un.RemoveAppDataPage un.RemoveAppDataPageLeave" in script
    assert "&Remove application data" in script
    assert "${If} $RemoveAppDataState == ${BST_CHECKED}" in script
    assert 'RMDir /r "$LOCALAPPDATA\\${APP_NAME}"' in script


def test_python_sources_carry_spdx_headers() -> None:
    python_roots = (REPO_ROOT / "build", REPO_ROOT / "src", REPO_ROOT / "tests")
    missing_headers: list[str] = []

    for root in python_roots:
        for path in sorted(root.rglob("*.py")):
            lines = path.read_text(encoding="utf-8").splitlines()
            if not lines:
                missing_headers.append(str(path.relative_to(REPO_ROOT)))
                continue

            header_index = 1 if lines[0].startswith("#!") else 0
            if (
                len(lines) <= header_index
                or lines[header_index] != "# SPDX-License-Identifier: GPL-3.0-or-later"
            ):
                missing_headers.append(str(path.relative_to(REPO_ROOT)))

    assert not missing_headers
