# SPDX-License-Identifier: GPL-3.0-or-later
"""Unit tests for bundled third-party notice generation (§2.3, §12.2)."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path


def _load_module():
    module_path = Path(__file__).resolve().parents[2] / "build" / "generate_third_party.py"
    spec = importlib.util.spec_from_file_location("generate_third_party", module_path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


class _FakeMetadata:
    def __init__(self, data: dict[str, str], multi: dict[str, list[str]] | None = None) -> None:
        self._data = data
        self._multi = multi or {}

    def get(self, key: str, default: str | None = None) -> str | None:
        return self._data.get(key, default)

    def get_all(self, key: str, default: list[str] | None = None) -> list[str]:
        return list(self._multi.get(key, default or []))


class _FakeDistribution:
    def __init__(self, version: str, metadata_obj: _FakeMetadata) -> None:
        self.version = version
        self.metadata = metadata_obj


def test_load_package_notice_prefers_license_expression_and_project_url(monkeypatch) -> None:
    module = _load_module()

    def fake_distribution(_: str) -> _FakeDistribution:
        return _FakeDistribution(
            version="1.2.3",
            metadata_obj=_FakeMetadata(
                {
                    "License": "fallback-license",
                    "License-Expression": "GPL-3.0-only",
                    "Summary": "Example summary",
                },
                {"Project-URL": ["homepage, https://example.test/home"]},
            ),
        )

    monkeypatch.setattr(module.metadata, "distribution", fake_distribution)

    notice = module.load_package_notice(
        module.PackageSpec(
            distribution="example-dist",
            display_name="Example",
            role="Example role",
        )
    )

    assert notice.name == "Example"
    assert notice.version == "1.2.3"
    assert notice.license_name == "GPL-3.0-only"
    assert notice.homepage == "https://example.test/home"
    assert notice.summary == "Example summary"


def test_render_markdown_includes_manual_components_and_license_files() -> None:
    module = _load_module()

    output = module.render_markdown(
        [
            module.NoticeEntry(
                name="StormFuse",
                role="Application package",
                version="0.1.0",
                license_name="GPL-3.0-or-later",
                homepage="https://example.test/stormfuse",
                summary="Combine and compress video files using ffmpeg",
            ),
            *module.MANUAL_COMPONENTS,
        ]
    )

    assert "Generated by `build/generate_third_party.py`" in output
    assert "### FFmpeg (gyan.dev essentials build)" in output
    assert "PyInstaller, NSIS, pytest, ruff, mypy, and pylint" in output
    assert "- `GPL-3.0.txt` — StormFuse" in output
    assert "- `GPL-2.0.txt` — FFmpeg" in output
