# SPDX-License-Identifier: GPL-3.0-or-later
"""Tests for scripts/write_version.py."""

from __future__ import annotations

import importlib.util
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = REPO_ROOT / "scripts" / "write_version.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("write_version_under_test", SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)  # type: ignore[arg-type]
    assert spec is not None
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


write_version = _load_module()


def _init_repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.email", "t@t"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "T"], cwd=repo, check=True)
    subprocess.run(["git", "config", "commit.gpgsign", "false"], cwd=repo, check=True)
    return repo


def test_parse_tag_accepts_valid_form() -> None:
    assert write_version.parse_tag("v1.2.3") == "1.2.3"


def test_parse_tag_rejects_invalid_form() -> None:
    with pytest.raises(SystemExit):
        write_version.parse_tag("1.2.3")
    with pytest.raises(SystemExit):
        write_version.parse_tag("v1.2")


def test_write_version_file_creates_module(tmp_path: Path) -> None:
    target = tmp_path / "src" / "stormfuse" / "_version.py"
    write_version.write_version_file("1.2.3", target)
    assert target.exists()
    contents = target.read_text(encoding="utf-8")
    assert '__version__ = "1.2.3"' in contents
    assert "Generated by scripts/write_version.py" in contents


def test_derive_dev_version_without_git_returns_sentinel(tmp_path: Path) -> None:
    assert write_version.derive_dev_version(tmp_path) == "0.0.0+dev"


def test_derive_dev_version_on_exact_tag(tmp_path: Path) -> None:
    repo = _init_repo(tmp_path)
    (repo / "a").write_text("x\n")
    subprocess.run(["git", "add", "."], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-q", "-m", "x"], cwd=repo, check=True)
    subprocess.run(["git", "tag", "v1.2.3"], cwd=repo, check=True)
    assert write_version.derive_dev_version(repo) == "1.2.3"


def test_derive_dev_version_between_tags_includes_commit_count(tmp_path: Path) -> None:
    repo = _init_repo(tmp_path)
    (repo / "a").write_text("x\n")
    subprocess.run(["git", "add", "."], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-q", "-m", "x"], cwd=repo, check=True)
    subprocess.run(["git", "tag", "v1.2.3"], cwd=repo, check=True)
    (repo / "a").write_text("y\n")
    subprocess.run(["git", "add", "."], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-q", "-m", "y"], cwd=repo, check=True)
    version = write_version.derive_dev_version(repo)
    assert version.startswith("1.2.3+dev.1.g")


def test_cli_writes_version_file_with_explicit_tag(tmp_path: Path) -> None:
    repo = _init_repo(tmp_path)
    full_env = {**os.environ}
    full_env.pop("GITHUB_OUTPUT", None)
    result = subprocess.run(
        [sys.executable, str(SCRIPT_PATH), "--root", str(repo), "--tag", "v4.5.6"],
        env=full_env,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    assert result.stdout.strip() == "4.5.6"
    written = (repo / "src" / "stormfuse" / "_version.py").read_text(encoding="utf-8")
    assert '__version__ = "4.5.6"' in written
